flags: {}
packages:
- .
extra-deps:
- binary-0.8.7.0
- containers-0.5.11.0
- directory-1.3.4.0
- http-client-0.6.4
- language-glsl-0.3.0
- network-2.6.3.6
- process-1.6.5.1
- time-1.9.3
resolver: lts-13.28
